### ISSUE TITLE
Cordova / ionic app purchase events

### ISSUE THREAD

**Issue by maximnara** [yandexmobile/metrica-plugin-cordova#25]
Hello!
I'm struggling with sending purchase events on cordova/ionic app. Is there any way to use standard `reportEvent` method to send purchase and other event to have ARPU and other metrics?

Many thanks!

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12842445. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp16.05.2021, 03:01, "Maxim Luzhkov" ***@***.***>:
Hello!
I'm struggling with sending purchase events on cordova/ionic app. Is there any way to use standard reportEvent method to send purchase and other event to have ARPU and other metrics?
Many thanks!

**Comment by ghost** [comment]
Hello, Dear Maxim! In this case there is no possibility to send revenue/ecommerce events on cordova. But you can send data by reportEvent (you can send this data as parameters of events).--Пожалуйста, не забудьте оценить мой ответ  Настоящее сообщение и все приложения к нему предназначены только для их получателей и содержат конфиденциальную информацию и коммерческую тайну ООО «ЯНДЕКС». Их разглашение, передача третьим лицам либо иное распространение или копирование является нарушением прав ООО «ЯНДЕКС». Если вы получили настоящее сообщение по ошибке, пожалуйста, уведомите об этом отправителя и/или ООО «ЯНДЕКС» по электронной почте ответным письмом и удалите настоящее сообщение и/или всю переписку без возможности восстановления.   16.05.2021, 03:01, "Maxim Luzhkov" ***@***.***>:Hello!I'm struggling with sending purchase events on cordova/ionic app. Is there any way to use standard reportEvent method to send purchase and other event to have ARPU and other metrics?Many thanks!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maximnara** [comment]
All is ok
